language: R
sudo: false
cache: packages
after_success: if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'covr::coveralls(type
  = "all")'; fi
warnings_are_errors: true
before_deploy: if [ "$TRAVIS_OS_NAME" == "osx" ]; then rm -f *.tar.gz; fi
r_check_args: "--as-cran --install-args=--build"

deploy:
  provider: releases
  skip_cleanup: yes
  api_key:
    secure: GONi+7OmHaFIZgTHkfO7rGar5kNuFMKMp8EisDkIQwNujGGjVW75KDQojNFOkQonGTaa/P+N19dNOoPGMBf1ffE8L2f9kxVa2dvDKSgVoln27dShLorHOdRZb8531S3asZQhI5YNhSNV1AY9bWR2iRvWwsUHM89mI/NzQ3VVeXwS2qYTi6H7SDNcmSodgaD9iSvbbHqNLnxEtrU+wJOyL384EYEqJakHioi0q2o5VlkqR/q0KEqg3UfjtWIXUGJbk1IOJ0aS1vG/YbOqln2FqkhndngfDUrHpDqOml+hycUx6hIrNLcsqXO7ZNeuqXfvv1/hC2hW926G3hZx/MgQN2GFQxq7UW85cBxes0lqiQohaQ1UFI1MiBu1AfhAtCC7EfNPS2sdMiY2lTmNLxKwXBLilWD64+UP25ry4rKw7+/auk1+LFeXc+LegAjAyl9x9eyHoS0JaIJkfsxYsL0RHO+woqcZS7h+2p0UCrzoRey+N0RLWYBwT8vyYujS3hYWmCqq4IoNoT9URAitYlVJarrDk0Rd7Yy0MKi/Mb4Xv0UTh+AvoGmEn8Df9u8v0AxeT6gzvoO+YcJ4IXimnfHJ6ozamaYygg5ntqCoBa8id8TFZyqXEkGpApdcukQ9ulZlN6nH4rViaC1XxjGn1AWWdfRLx0Nz3K45pexAbi8iWsE=  
  file_glob: yes
  file: sri24*.t*gz
  on:
    repo: muschellij2/sri24

